### ISSUE TITLE
Errno::ENOENT (No such file or directory @ rb_file_s_stat - /tmp/sample_template.pdf)

### ISSUE THREAD

**Issue by DanielViglione** [FormAPI/libreconv#12]
I am using the following command:

```
Libreconv.convert(doc.docx, mypdf.pdf, soffice_path)
```

It has a docx file as first argument, a pdf file as second argument and the path to soffice -> /opt/libreoffice4.4/program/soffice. When I try to run this statement in production, I get the following error;

Errno::ENOENT (No such file or directory @ rb_file_s_stat - /tmp/sample_template.pdf):
  libreconv (0.9.0) lib/libreconv.rb:36:in `convert'
  libreconv (0.9.0) lib/libreconv.rb:10:in`convert'

How can I resolve this? And if it is the version of libreoffice that is causing this, what version should I use for this gem?

**Comment by ricn** [comment]
Hi,

Make sure the /tmp folder exists and that the user that runs the code have permission to write to /tmp.

**Comment by HenriqueKraemer** [comment]
Hi ricn, my tmp folder exists and i have permission to write on it... On my localhost is working ok, but in my Ubuntu Server (on amazon) im getting the same error, no matter what i do...

**Comment by diazweb** [comment]
Same problem over here, did you find any solution @HenriqueKraemer @ricn ?

Works great on development, but on production fails :-1:

**Comment by daneshd** [comment]
This may be related to the issue I found in #15 where `Spoon.spawnp` isn't actually running so the file that is trying to be `cp`ed isn't there.

**Comment by joshualaboratories** [comment]
I'm also experiencing the same issue

**Comment by faisalraza** [comment]
Experiencing the same issue. The gem is tested for LibreOffice 4.4 according to the documentation.

**Comment by ashish-d** [comment]
Faced the same issue on Production.

Turns out there was a stale instance of `libreoffice` that was preventing new conversions. 

Killing it fixed this issue for me.

Version: LibreOffice 4.2.8.2 420m0(Build:2)

**Comment by ndbroadbent** [comment]
Hi everyone, I think this should be fixed now. I just need to release a new version of the gem.

**Comment by lukash10** [comment]
Some solution? In production still error on /tmp...
