### ISSUE TITLE
IOError: Can't find Libreoffice or Openoffice executable.

### ISSUE THREAD

**Issue by vkeziah** [FormAPI/libreconv#18]
I am trying to use this gem but getting the following error on mac os X eventhough I installed Libreoffice

IOError: Can't find Libreoffice or Openoffice executable.

**Comment by skancherla-drg** [comment]
you need to set path to soffice

**Comment by ndbroadbent** [comment]
Please follow these instructions to install LibreOffice:

* Linux: `sudo apt-get install libreoffice`
* Mac: `brew cask install libreoffice`

**Comment by monteirobrena** [comment]
I installed without the recommendations and suggestions:

`sudo apt-get install libreoffice  --no-install-recommends --no-install-suggests`

**Comment by manuel1280** [comment]
Hi, I have the same problem but in production. I tried to install the buildpack with https://elements.heroku.com/buildpacks/bluetealondon/heroku-buildpack-libreoffice-for-heroku-18 , but does not work for me. Some tutorial to show how do this correctly?. Thanks!
